package addressbook;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;

public class GroupCreationTests extends TestBase{

    @Test
    public void testGroupCreation() {
        gotoGroupPage();
        initGroupCreation();
        fillGroupForm();
        submitGroupCreation();
        logout();
    }

}
